# See <https://github.com/rust-lang/mdBook/blob/master/book-example/src/continuous-integration.md>.

language: rust
sudo: false

cache:
  - cargo

rust:
  - stable

env:
  - VERSION=0.4.5 TARGET_LANG=ja

before_script:
  - curl -LO https://github.com/rust-lang-nursery/mdBook/releases/download/v${VERSION}/mdbook-v${VERSION}-x86_64-unknown-linux-gnu.tar.gz
  - tar xf mdbook-v${VERSION}-x86_64-unknown-linux-gnu.tar.gz

script:
  - mkdir -p pages && ./mdbook build ${TARGET_LANG} && ./mdbook test ${TARGET_LANG} && test ! -e pages/${TARGET_LANG} && mv ${TARGET_LANG}/book pages/${TARGET_LANG}

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: pages
  keep-history: false
  on:
    branch: master
